# Generated by Django 5.0.9 on 2026-01-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('freelancer_id', models.IntegerField()),
                ('cover_letter', models.TextField()),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time_days', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
